### PR TITLE
fix bridging of interfaces (fixes #152)

### LINKED ISSUE #152: treehouses bridge not bridging internet

### PR DESCRIPTION
**Pull request by i5o**

### CODE REVIEW

File: templates/network/up-bridge.sh [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+# Flush rules
+iptables -t nat -F
+iptables -F
+
+# Apply new rules
+iptables -t nat -A POSTROUTING -o $SOURCE_INTERFACE -j MASQUERADE
+iptables -A FORWARD -i $SOURCE_INTERFACE -o $AP_INTERFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
+iptables -A FORWARD -i $AP_INTERFACE -j ACCEPT
+
+while /bin/true;
```
Comment (i5o) [inline templates/network/up-bridge.sh]: This while will run in background because of "&" so it doesn't freeze the system

File: templates/network/up-bridge.sh [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+do
+  while ! ifconfig wlan0 2>/dev/null | grep "inet " -q;
```
Comment (i5o) [inline templates/network/up-bridge.sh]: while wlan0 has no ip wait for one

File: templates/network/up-bridge.sh [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  do
+      sleep 1
+      echo "Waiting for wlan0 to have an ip."
+  done
+  echo "Ok. wlan0 has an ip"
+
+  ips=$(ip r | sed -n '/default .* wlan0 .* metric .*/p' | head -n1 | sed -n 's/metric .*/metric 1/p')
```
Comment (i5o) [inline templates/network/up-bridge.sh]: we find the current wlan0 metric and change it number to 1 -> the first one
highest priority => first interface where the traffic will go => traffic of bridge

File: templates/network/up-bridge.sh [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+  ip r add $ips
```
Comment (i5o) [inline templates/network/up-bridge.sh]: I can't use "$ips" because ip r will complain..
`Error: any valid prefix is expected rather than "asd".`

File: templates/network/up-bridge.sh [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+  break
```
Comment (i5o) [inline templates/network/up-bridge.sh]: we leave the background loop

File: templates/network/wlan0/bridge [hunk 6]
```diff
@@ -2,4 +2,6 @@ allow-hotplug ap0
 auto ap0
 iface ap0 inet static
     address 192.168.2.1
-    netmask 255.255.255.0
\ No newline at end of file
+    netmask 255.255.255.0
+
+post-up /etc/network/up-bridge.sh
```
Comment (i5o) [inline templates/network/wlan0/bridge]: after the interface is up we run `/etc/network/up-bridge.sh`
