### PR TITLE
`treehouses services <service> install` sleepy try (fixes #946)

### LINKED ISSUE #946: service install retry not really useful so far
Every time i run into this. I think it might be better to have some time inbetween the retries? Like maybe 5-10 seconds? I think 3 retries total with 10 seconds between each try for a total time of function running of 30-40 seconds would be better. 

```
 ✗  services couchdb install
   (from function `assert_success' in file /usr/lib/node_modules/bats-assert/src/assert.bash, line 113,
    in test file services/couchdb.bats, line 11)
     `assert_success && assert_output -p 'installed'' failed

   -- command failed --
   status : 1
   output (11 lines):
Pulling couchdb ... error

     ERROR: for couchdb  b'Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:33302->127.0.0.1:53: read: connection refused'
     Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:33302->127.0.0.1:53: read: connection refused
     retrying pull
Pulling couchdb ... error

     ERROR: for couchdb  b'Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:33316->127.0.0.1:53: read: connection refused'
     Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:33316->127.0.0.1:53: read: connection refused
     retrying pull
     ERROR: cannot pull docker image
   --
```

### PR DESCRIPTION
**Pull request by LordJashin32**
```bash
root@treehouses:~/cli# ./cli.sh services nextcloud install
Pulling nextcloud ... done
nextcloud installed
modify default environment variables by running 'cli.sh services nextcloud environment edit'
root@treehouses:~/cli# ./cli.sh services mongodb install
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: cannot pull docker image
root@treehouses:~/cli#

```

### CODE REVIEW

File: modules/services.sh [hunk 1]
```diff
@@ -100,10 +100,11 @@ function services {
             fi
           elif source $SERVICES/install-${service_name}.sh && install ; then
             retries=0
-            while [ "$retries" -lt 2 ];
+            while [ "$retries" -lt 5 ];
             do
               if ! docker-compose --project-directory /srv/$service_name -f /srv/${service_name}/${service_name}.yml pull ; then
-                echo "retrying pull"
+                echo "retrying pull in 6 seconds"
+                sleep 6
```
Comment (kjong) [inline modules/services.sh:107]: I was thinking about encapsulating the `echo` (and `sleep` in this case) in an `if [ "$retries" -lt 4 ];` so that it's not printed after the last pull attempt (since its not actually pulling again after that last one).

Comment (LordJashin32) [reply modules/services.sh:107]: Good idea.

**Comment by LordJashin32** [comment]
```bash
root@treehouses:~/cli# ./cli.sh services mongodb install
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
retrying pull in 6 seconds
ERROR: The Compose file '/srv/mongodb/mongodb.yml' is invalid because:
services.mongodb.environment contains an invalid type, it should be an object, or an array
ERROR: cannot pull docker image
root@treehouses:~/cli#
```
