### PR TITLE
fix wrong command output (fixes #284)

### LINKED ISSUE #284: treehouses openvpn from on/off to start/stop
in message when not active triggered by `treehouses openvpn`

### PR DESCRIPTION
**Pull request by i5o**

### CODE REVIEW

File: fix_routes.sh [hunk 1]
```diff
@@ -0,0 +1,2 @@
+ip r del 0.0.0.0/1 via 192.168.255.5 dev tun0
```
Comment (dogi) [inline fix_routes.sh]: think this file is too much
