### PR TITLE
`treehouses led diwali` iterations (fixes #1518) (fixes #1520)

### LINKED ISSUE #1518: led diwali incorrect number of iterations
In led.sh, the code for the diwali pattern loops all of the steps 6 times instead of 5.
```
 for i in {0..5}                            # Green LED
  do
    set_brightness 0 1 && sleep 0.025        # green on
    set_brightness 0 0 && sleep 0.025        # green OFF
  done

  for i in {0..5}                            # Red LED
  do
    set_brightness 1 1 && sleep 0.025        # red on
    set_brightness 1 0 && sleep 0.025        # red OFF
  done

  for i in {0..5}                            # Both LEDs
  do
    set_brightness 1 1 && set_brightness 0 1
    ...
  done
```
Reference:

> diwali)
      checkroot
      echo "leds are set to diwali mode."
      echo "Look at your RPi leds, both leds will be in this pattern..."
      echo "Green LED: 0.025 on; 0.025 off; this will happen 5 times"
      echo "Red LED: 0.025 on; 0.025 off; this will happen 5 times"
      echo "Both LED: flash 10 times; this will happen 5 times"
      diwali > "$LOGFILE"
      ;;

### LINKED ISSUE #1520: led diwali incorrect number of flashes
In the last step of diwali pattern from led.sh it says to flash 10 times
> diwali)
      ...
      echo "Both LED: flash 10 times; this will happen 5 times"
      diwali > "$LOGFILE"

Yet, in  the code it only does it 5 times, as setting it on and off counts as 1 flash.
```
for i in {0..5}                            # Both LEDs
  do
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
    sleep 0.025
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
    sleep 0.025
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
    sleep 0.025
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
    sleep 0.025
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
  done
```
I believe there should be 5 more flashes in the loop body.

### PR DESCRIPTION
**Pull request by dyeh123**
Fixes #1518 
Fixes #1520

### CODE REVIEW

File: modules/led.sh [hunk 1]
```diff
@@ -534,6 +534,26 @@ function diwali {
...
+    sleep 0.025
+    set_brightness 1 0 && set_brightness 0 0
+    sleep 0.025
+    set_brightness 1 1 && set_brightness 0 1
+    sleep 0.025
+    set_brightness 1 0 && set_brightness 0 0
+    sleep 0.025
+    set_brightness 1 1 && set_brightness 0 1
+    sleep 0.025
+    set_brightness 1 0 && set_brightness 0 0
```
Comment (fankaiyuan) [inline modules/led.sh:556]: can be put in an inner loop
```shell
for j in {0..9}
do
    set_brightness 1 1 && set_brightness 0 1
    sleep 0.025
    set_brightness 1 0 && set_brightness 0 0
    sleep 0.025
done
```

Comment (sarahrams) [reply modules/led.sh:556]: This would work fine!
