### PR TITLE
`treehouses upgrade bluetooth` targeted kill (fixes #1607)

### LINKED ISSUE #1607: `treehouses upgrade bluetooth <branch>` is crashing also wifi
we maybe should stop bluetooth before upgrading
`treehouses bluetooth stop`
upgrade
and then start again

if we do all of that while running this in a screen
we can upgrade also being connected over bluetooth

### PR DESCRIPTION
**Pull request by ComputerOnFire**
improves the bluetooth upgrade function to work when sent from remote. requires an up to date treehouses image, or make sure your rpibluetooth service is the same as master https://github.com/treehouses/builder/blob/master/install/etc/systemd/system/rpibluetooth.service

- fixes #1607

### CODE REVIEW

File: modules/upgrade.sh [hunk 1]
```diff
@@ -44,6 +44,7 @@ function upgrade {
     fi
     cp /usr/local/bin/bluetooth-server.py "/usr/local/bin/bluetooth-server.py.$(date +'%Y%m%d%H%m%S')"
     curl -s "https://raw.githubusercontent.com/treehouses/control/${branch}/server.py" -o /usr/local/bin/bluetooth-server.py
+    pkill -f bluetooth-server.py
```
Comment (ComputerOnFire) [inline modules/upgrade.sh:47]: check for version? (post release-135)

Comment (ComputerOnFire) [reply modules/upgrade.sh:47]: `grep -q "Restart=always" /etc/systemd/system/rpibluetooth.service`
